import type { Locale } from "../config";

const messages = {
  ko: { title: "가젯·스타파워 주인 맞히기", description: "가젯이나 스타파워의 이름을 보고 주인을 찾아보세요.", metaDescription: "가젯과 스타파워의 주인이 누구인지 맞히는 10문제 브롤스타즈 퀴즈입니다.", rules: "능력 이름을 보고 해당 브롤러를 네 가지 보기에서 고르세요. 정답은 한 번만 제출할 수 있습니다.", pool: "출제 가능한 능력 {count}개", mixed: "가젯 + 스타파워", gadgets: "가젯만", starPowers: "스타파워만", gadget: "가젯", starPower: "스타파워", imageAlt: "능력 아이콘", prompt: "이 능력을 가진 브롤러는 누구일까요?", noAbilities: "이 모드에서 출제할 수 있는 능력이 부족합니다." },
  en: { title: "Gadget & Star Power Owner Quiz", description: "Match each Gadget or Star Power to its brawler.", metaDescription: "Take a 10-question Brawl Stars quiz and match Gadgets and Star Powers to their owners.", rules: "Read the ability name and choose its brawler from four options. Each question allows one answer.", pool: "{count} abilities available", mixed: "Gadgets + Star Powers", gadgets: "Gadgets only", starPowers: "Star Powers only", gadget: "Gadget", starPower: "Star Power", imageAlt: "Ability icon", prompt: "Which brawler has this ability?", noAbilities: "There are not enough abilities in this mode for a playable quiz." },
  ja: { title: "ガジェット・スターパワーの持ち主クイズ", description: "ガジェットやスターパワーから持ち主のブロウラーを当てましょう。", metaDescription: "ガジェットとスターパワーの持ち主を当てる全10問のBrawl Starsクイズです。", rules: "能力名を見て、4人の候補から持ち主を選びます。回答は各問題1回です。", pool: "出題できる能力：{count}個", mixed: "ガジェット＋スターパワー", gadgets: "ガジェットのみ", starPowers: "スターパワーのみ", gadget: "ガジェット", starPower: "スターパワー", imageAlt: "能力アイコン", prompt: "この能力を持つブロウラーは？", noAbilities: "このモードには出題できる能力が足りません。" },
  "pt-br": { title: "Quiz: dono do Acessório e Poder de Estrela", description: "Descubra a qual brawler pertence cada habilidade.", metaDescription: "Um quiz de 10 perguntas para associar Acessórios e Poderes de Estrela aos seus brawlers.", rules: "Leia o nome da habilidade e escolha o brawler entre quatro opções. Há uma resposta por pergunta.", pool: "Habilidades disponíveis: {count}", mixed: "Acessórios + Poderes de Estrela", gadgets: "Só Acessórios", starPowers: "Só Poderes de Estrela", gadget: "Acessório", starPower: "Poder de Estrela", imageAlt: "Ícone da habilidade", prompt: "Qual brawler tem esta habilidade?", noAbilities: "Este modo ainda não tem habilidades suficientes para jogar." },
  es: { title: "Adivina quién tiene el gadget o poder estelar", description: "Relaciona cada habilidad con su brawler.", metaDescription: "Un cuestionario de 10 preguntas para asociar gadgets y poderes estelares con sus brawlers.", rules: "Lee el nombre de la habilidad y elige al brawler entre cuatro opciones. Solo hay un intento por pregunta.", pool: "Habilidades disponibles: {count}", mixed: "Gadgets + poderes estelares", gadgets: "Solo gadgets", starPowers: "Solo poderes estelares", gadget: "Gadget", starPower: "Poder estelar", imageAlt: "Icono de la habilidad", prompt: "¿Qué brawler tiene esta habilidad?", noAbilities: "Aún no hay suficientes habilidades para jugar en este modo." },
  tr: { title: "Aygıt ve Yıldız Gücü Sahibi Testi", description: "Her yeteneğin hangi savaşçıya ait olduğunu bul.", metaDescription: "Aygıtları ve Yıldız Güçlerini savaşçılarıyla eşleştiren 10 soruluk test.", rules: "Yeteneğin adını oku ve dört seçenekten savaşçısını seç. Her soru için bir cevap hakkın var.", pool: "Oynanabilir yetenek: {count}", mixed: "Aygıtlar + Yıldız Güçleri", gadgets: "Yalnızca aygıtlar", starPowers: "Yalnızca Yıldız Güçleri", gadget: "Aygıt", starPower: "Yıldız Gücü", imageAlt: "Yetenek simgesi", prompt: "Bu yetenek hangi savaşçıda?", noAbilities: "Bu modda oynanabilecek yeterli yetenek yok." },
  de: { title: "Gadget- und Starpower-Besitzerquiz", description: "Ordne jedes Gadget und jede Starpower dem Brawler zu.", metaDescription: "Ein Brawl-Stars-Quiz mit zehn Fragen zu den Besitzern von Gadgets und Starpowers.", rules: "Lies den Namen der Fähigkeit und wähle den Brawler aus vier Optionen. Pro Frage gibt es einen Versuch.", pool: "{count} Fähigkeiten verfügbar", mixed: "Gadgets + Starpowers", gadgets: "Nur Gadgets", starPowers: "Nur Starpowers", gadget: "Gadget", starPower: "Starpower", imageAlt: "Fähigkeitssymbol", prompt: "Welcher Brawler hat diese Fähigkeit?", noAbilities: "Für diesen Modus gibt es noch nicht genug Fähigkeiten." },
  fr: { title: "Quiz des gadgets et pouvoirs star", description: "Associez chaque capacité au brawler qui la possède.", metaDescription: "Un quiz de 10 questions pour associer gadgets et pouvoirs star aux brawlers.", rules: "Lisez le nom de la capacité et choisissez le brawler parmi quatre propositions. Une réponse par question.", pool: "Capacités disponibles : {count}", mixed: "Gadgets + pouvoirs star", gadgets: "Gadgets uniquement", starPowers: "Pouvoirs star uniquement", gadget: "Gadget", starPower: "Pouvoir star", imageAlt: "Icône de la capacité", prompt: "Quel brawler possède cette capacité ?", noAbilities: "Il n’y a pas encore assez de capacités pour ce mode." },
  it: { title: "Quiz: proprietario di gadget e abilità stellare", description: "Abbina ogni abilità al brawler che la possiede.", metaDescription: "Un quiz di 10 domande per associare gadget e abilità stellari ai brawler.", rules: "Leggi il nome dell’abilità e scegli il brawler tra quattro opzioni. Una risposta per domanda.", pool: "Abilità disponibili: {count}", mixed: "Gadget + abilità stellari", gadgets: "Solo gadget", starPowers: "Solo abilità stellari", gadget: "Gadget", starPower: "Abilità stellare", imageAlt: "Icona dell’abilità", prompt: "Quale brawler possiede questa abilità?", noAbilities: "Non ci sono ancora abbastanza abilità per questa modalità." },
  ru: { title: "Викторина: гаджеты и звёздные силы", description: "Определите, какому бойцу принадлежит способность.", metaDescription: "Викторина из 10 вопросов о владельцах гаджетов и звёздных сил Brawl Stars.", rules: "Прочитайте название способности и выберите бойца из четырёх вариантов. На вопрос даётся одна попытка.", pool: "Доступно способностей: {count}", mixed: "Гаджеты + звёздные силы", gadgets: "Только гаджеты", starPowers: "Только звёздные силы", gadget: "Гаджет", starPower: "Звёздная сила", imageAlt: "Значок способности", prompt: "Какой боец обладает этой способностью?", noAbilities: "В этом режиме пока недостаточно способностей для игры." },
} as const satisfies Record<Locale, Record<string, string>>;

export type AbilityQuizMessages = (typeof messages)["ko"];
export function getAbilityQuizMessages(locale: Locale): AbilityQuizMessages { return messages[locale] as AbilityQuizMessages; }
