import type { Locale } from "../config";

const messages = {
  ko: { title: "맵 이름 맞히기", description: "맵 이미지를 보고 이름을 골라 보세요.", metaDescription: "Brawl Stars 맵 이미지를 보고 이름을 맞히는 10문제 미니게임입니다.", rules: "맵 그림을 보고 네 가지 보기 중 이름을 선택하세요. 정답은 한 번만 제출할 수 있습니다.", pool: "출제 가능한 맵 {count}개", imageAlt: "맵 이미지", prompt: "이 맵의 이름은 무엇일까요?", noMaps: "출제할 수 있는 맵이 부족합니다." },
  en: { title: "Map Name Quiz", description: "Look at the map and choose its name.", metaDescription: "Identify Brawl Stars maps in a 10-question picture quiz.", rules: "Look at the map image and choose its name from four options. Each answer can be submitted once.", pool: "{count} maps available", imageAlt: "Map image", prompt: "What is this map called?", noMaps: "There are not enough maps for a playable quiz." },
  ja: { title: "マップ名クイズ", description: "マップ画像を見て名前を選びましょう。", metaDescription: "Brawl Starsのマップ画像を見て名前を当てる全10問のクイズです。", rules: "マップ画像を見て、4つの選択肢から名前を選びます。回答は各問題1回です。", pool: "出題できるマップ：{count}件", imageAlt: "マップ画像", prompt: "このマップの名前は？", noMaps: "クイズに必要なマップが足りません。" },
  "pt-br": { title: "Quiz de nomes de mapas", description: "Veja o mapa e escolha o nome correto.", metaDescription: "Identifique mapas de Brawl Stars em um quiz visual de 10 perguntas.", rules: "Observe a imagem e escolha o nome entre quatro opções. Cada pergunta permite uma resposta.", pool: "Mapas disponíveis: {count}", imageAlt: "Imagem do mapa", prompt: "Qual é o nome deste mapa?", noMaps: "Ainda não há mapas suficientes para jogar." },
  es: { title: "Adivina el nombre del mapa", description: "Mira el mapa y elige su nombre.", metaDescription: "Identifica mapas de Brawl Stars en un cuestionario visual de 10 preguntas.", rules: "Mira la imagen y elige el nombre entre cuatro opciones. Solo puedes responder una vez por pregunta.", pool: "Mapas disponibles: {count}", imageAlt: "Imagen del mapa", prompt: "¿Cómo se llama este mapa?", noMaps: "Aún no hay suficientes mapas para jugar." },
  tr: { title: "Harita Adı Testi", description: "Haritaya bak ve adını seç.", metaDescription: "10 soruluk görsel testte Brawl Stars haritalarının adlarını bul.", rules: "Harita görseline bak ve dört seçenekten adını seç. Her soruda bir cevap hakkın var.", pool: "Oynanabilir harita: {count}", imageAlt: "Harita görseli", prompt: "Bu haritanın adı ne?", noMaps: "Oynanabilecek yeterli harita yok." },
  de: { title: "Karten-Namenquiz", description: "Sieh dir die Karte an und wähle ihren Namen.", metaDescription: "Erkenne Brawl-Stars-Karten in einem Bilderquiz mit zehn Fragen.", rules: "Sieh dir das Kartenbild an und wähle den Namen aus vier Optionen. Pro Frage ist eine Antwort möglich.", pool: "{count} Karten verfügbar", imageAlt: "Kartenbild", prompt: "Wie heißt diese Karte?", noMaps: "Es gibt noch nicht genug Karten für ein Quiz." },
  fr: { title: "Quiz des noms de cartes", description: "Regardez la carte et choisissez son nom.", metaDescription: "Identifiez les cartes de Brawl Stars dans un quiz illustré de 10 questions.", rules: "Observez la carte et choisissez son nom parmi quatre propositions. Une réponse est possible par question.", pool: "Cartes disponibles : {count}", imageAlt: "Image de la carte", prompt: "Quel est le nom de cette carte ?", noMaps: "Il n’y a pas encore assez de cartes pour jouer." },
  it: { title: "Quiz sui nomi delle mappe", description: "Guarda la mappa e scegli il suo nome.", metaDescription: "Riconosci le mappe di Brawl Stars in un quiz illustrato da 10 domande.", rules: "Osserva l’immagine e scegli il nome tra quattro opzioni. Puoi rispondere una sola volta per domanda.", pool: "Mappe disponibili: {count}", imageAlt: "Immagine della mappa", prompt: "Come si chiama questa mappa?", noMaps: "Non ci sono ancora abbastanza mappe per giocare." },
  ru: { title: "Викторина по названиям карт", description: "Посмотрите на карту и выберите её название.", metaDescription: "Угадайте карты Brawl Stars в викторине из 10 вопросов с изображениями.", rules: "Посмотрите на изображение и выберите название из четырёх вариантов. На каждый вопрос даётся одна попытка.", pool: "Доступно карт: {count}", imageAlt: "Изображение карты", prompt: "Как называется эта карта?", noMaps: "Пока недостаточно карт для игры." },
} as const satisfies Record<Locale, Record<string, string>>;

export type MapQuizMessages = (typeof messages)["ko"];
export function getMapQuizMessages(locale: Locale): MapQuizMessages { return messages[locale] as MapQuizMessages; }
