import type { Locale } from "../config";

const messages = {
  ko: { question: "문제", score: "점수", next: "다음 문제", results: "결과 보기", endSession: "여기서 종료", correct: "정답입니다.", incorrect: "아쉽지만 오답입니다.", loading: "이미지를 불러오는 중입니다.", imageFailed: "이미지를 불러오지 못해 다음 문제로 넘어갑니다.", dataUnavailable: "게임 데이터를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.", insufficient: "플레이할 수 있는 문제가 아직 부족합니다.", best: "최고 기록: {score} / 10 ({percentage}%)", noBest: "아직 기록이 없습니다.", completed: "완료한 문제: {completed} / 10", recap: "이번 도전 정답", earlyEnd: "{completed}문제를 완료하고 도전을 마쳤습니다.", restart: "다시 도전", backToHub: "미니게임으로 돌아가기", start: "게임 시작", chooseMode: "게임 모드", tenQuestions: "10문제 도전", percentage: "정답률" },
  en: { question: "Question", score: "Score", next: "Next question", results: "View results", endSession: "End session", correct: "Correct.", incorrect: "Not quite.", loading: "Loading image.", imageFailed: "This image could not load. Moving to another question.", dataUnavailable: "Game data could not be loaded. Please try again shortly.", insufficient: "There are not enough playable questions yet.", best: "Personal best: {score} / 10 ({percentage}%)", noBest: "No record yet.", completed: "Questions completed: {completed} / 10", recap: "Answers from this run", earlyEnd: "You ended the run after {completed} questions.", restart: "Play again", backToHub: "Back to Mini Games", start: "Start game", chooseMode: "Game mode", tenQuestions: "10-question challenge", percentage: "Accuracy" },
  ja: { question: "問題", score: "スコア", next: "次の問題", results: "結果を見る", endSession: "ここで終了", correct: "正解です。", incorrect: "残念、不正解です。", loading: "画像を読み込んでいます。", imageFailed: "画像を読み込めなかったため、次の問題へ進みます。", dataUnavailable: "ゲームデータを読み込めませんでした。しばらくしてから再度お試しください。", insufficient: "出題できる問題がまだ足りません。", best: "自己ベスト：{score} / 10（{percentage}%）", noBest: "記録はまだありません。", completed: "回答した問題：{completed} / 10", recap: "今回の正解", earlyEnd: "{completed}問を終えてチャレンジを終了しました。", restart: "もう一度挑戦", backToHub: "ミニゲームに戻る", start: "ゲーム開始", chooseMode: "ゲームモード", tenQuestions: "全10問に挑戦", percentage: "正答率" },
  "pt-br": { question: "Pergunta", score: "Pontuação", next: "Próxima pergunta", results: "Ver resultado", endSession: "Encerrar partida", correct: "Acertou.", incorrect: "Não foi dessa vez.", loading: "Carregando imagem.", imageFailed: "Não foi possível carregar a imagem. Vamos para outra pergunta.", dataUnavailable: "Não foi possível carregar os dados do jogo. Tente novamente em instantes.", insufficient: "Ainda não há perguntas jogáveis suficientes.", best: "Recorde pessoal: {score} / 10 ({percentage}%)", noBest: "Ainda sem recorde.", completed: "Perguntas concluídas: {completed} / 10", recap: "Acertos desta partida", earlyEnd: "Você encerrou a partida após {completed} perguntas.", restart: "Jogar novamente", backToHub: "Voltar aos minijogos", start: "Começar", chooseMode: "Modo de jogo", tenQuestions: "Desafio de 10 perguntas", percentage: "Precisão" },
  es: { question: "Pregunta", score: "Puntuación", next: "Siguiente pregunta", results: "Ver resultado", endSession: "Terminar partida", correct: "Correcto.", incorrect: "Esta vez no.", loading: "Cargando imagen.", imageFailed: "No se pudo cargar la imagen. Pasamos a otra pregunta.", dataUnavailable: "No se pudieron cargar los datos del juego. Inténtalo de nuevo en un momento.", insufficient: "Aún no hay suficientes preguntas disponibles.", best: "Mejor marca: {score} / 10 ({percentage}%)", noBest: "Aún no hay récord.", completed: "Preguntas completadas: {completed} / 10", recap: "Aciertos de esta partida", earlyEnd: "Terminaste la partida después de {completed} preguntas.", restart: "Jugar otra vez", backToHub: "Volver a minijuegos", start: "Empezar", chooseMode: "Modo de juego", tenQuestions: "Desafío de 10 preguntas", percentage: "Precisión" },
  tr: { question: "Soru", score: "Puan", next: "Sonraki soru", results: "Sonucu gör", endSession: "Oyunu bitir", correct: "Doğru.", incorrect: "Bu kez olmadı.", loading: "Görsel yükleniyor.", imageFailed: "Görsel yüklenemedi. Başka bir soruya geçiliyor.", dataUnavailable: "Oyun verileri yüklenemedi. Biraz sonra tekrar dene.", insufficient: "Henüz oynanabilecek yeterli soru yok.", best: "En iyi sonuç: {score} / 10 (%{percentage})", noBest: "Henüz rekor yok.", completed: "Tamamlanan soru: {completed} / 10", recap: "Bu oyundaki doğru cevaplar", earlyEnd: "Oyunu {completed} sorudan sonra bitirdin.", restart: "Tekrar oyna", backToHub: "Mini Oyunlara dön", start: "Oyuna başla", chooseMode: "Oyun modu", tenQuestions: "10 soruluk meydan okuma", percentage: "Doğruluk" },
  de: { question: "Frage", score: "Punkte", next: "Nächste Frage", results: "Ergebnis ansehen", endSession: "Runde beenden", correct: "Richtig.", incorrect: "Leider falsch.", loading: "Bild wird geladen.", imageFailed: "Das Bild konnte nicht geladen werden. Es geht mit einer anderen Frage weiter.", dataUnavailable: "Spieldaten konnten nicht geladen werden. Bitte versuche es gleich noch einmal.", insufficient: "Es gibt noch nicht genug spielbare Fragen.", best: "Persönlicher Bestwert: {score} / 10 ({percentage} %) ", noBest: "Noch kein Rekord.", completed: "Beantwortete Fragen: {completed} / 10", recap: "Richtige Antworten in dieser Runde", earlyEnd: "Du hast die Runde nach {completed} Fragen beendet.", restart: "Noch einmal spielen", backToHub: "Zurück zu den Minispielen", start: "Spiel starten", chooseMode: "Spielmodus", tenQuestions: "Herausforderung mit 10 Fragen", percentage: "Trefferquote" },
  fr: { question: "Question", score: "Score", next: "Question suivante", results: "Voir le résultat", endSession: "Terminer la partie", correct: "Bonne réponse.", incorrect: "Ce n’est pas la bonne réponse.", loading: "Chargement de l’image.", imageFailed: "L’image n’a pas pu être chargée. Passage à une autre question.", dataUnavailable: "Impossible de charger les données du jeu. Réessayez dans un instant.", insufficient: "Il n’y a pas encore assez de questions jouables.", best: "Meilleur score : {score} / 10 ({percentage} %)", noBest: "Aucun record pour le moment.", completed: "Questions terminées : {completed} / 10", recap: "Bonnes réponses de cette partie", earlyEnd: "Vous avez terminé la partie après {completed} questions.", restart: "Rejouer", backToHub: "Retour aux mini-jeux", start: "Commencer", chooseMode: "Mode de jeu", tenQuestions: "Défi en 10 questions", percentage: "Précision" },
  it: { question: "Domanda", score: "Punteggio", next: "Domanda successiva", results: "Vedi il risultato", endSession: "Termina la partita", correct: "Esatto.", incorrect: "Non è corretto.", loading: "Caricamento immagine.", imageFailed: "Impossibile caricare l’immagine. Passiamo a un’altra domanda.", dataUnavailable: "Impossibile caricare i dati del gioco. Riprova tra poco.", insufficient: "Non ci sono ancora abbastanza domande disponibili.", best: "Record personale: {score} / 10 ({percentage}%)", noBest: "Nessun record per ora.", completed: "Domande completate: {completed} / 10", recap: "Risposte corrette di questa partita", earlyEnd: "Hai terminato la partita dopo {completed} domande.", restart: "Gioca ancora", backToHub: "Torna ai minigiochi", start: "Inizia", chooseMode: "Modalità di gioco", tenQuestions: "Sfida da 10 domande", percentage: "Precisione" },
  ru: { question: "Вопрос", score: "Очки", next: "Следующий вопрос", results: "Показать результат", endSession: "Завершить игру", correct: "Верно.", incorrect: "Неверно.", loading: "Загрузка изображения.", imageFailed: "Не удалось загрузить изображение. Переходим к другому вопросу.", dataUnavailable: "Не удалось загрузить данные игры. Попробуйте ещё раз позже.", insufficient: "Пока недостаточно вопросов для игры.", best: "Рекорд: {score} / 10 ({percentage}%)", noBest: "Рекорда пока нет.", completed: "Пройдено вопросов: {completed} / 10", recap: "Верные ответы в этой игре", earlyEnd: "Вы завершили игру после {completed} вопросов.", restart: "Сыграть ещё раз", backToHub: "К мини-играм", start: "Начать игру", chooseMode: "Режим игры", tenQuestions: "Испытание из 10 вопросов", percentage: "Точность" },
} as const satisfies Record<Locale, Record<string, string>>;

export type RoundMessages = (typeof messages)["ko"];
export function getRoundMessages(locale: Locale): RoundMessages {
  return messages[locale] as RoundMessages;
}
