import type { Locale } from "../config";

const messages = {
  ko: { title: "브롤러 실루엣 퀴즈", description: "실루엣을 보고 브롤러 이름을 맞혀 보세요.", metaDescription: "브롤러 실루엣을 보고 이름을 맞히는 10문제 도전에 참여해 보세요.", rules: "그림자만 보고 브롤러 이름을 입력하세요. 한 문제마다 한 번 답할 수 있습니다.", pool: "출제 가능한 기본 브롤러 {count}명", baseMode: "기본 브롤러", skinsMode: "스킨 포함", expertMode: "실루엣 전문가", skinUnavailable: "적절한 스킨 이미지가 준비되지 않아 이 모드는 아직 플레이할 수 없습니다.", inputLabel: "브롤러 이름", inputPlaceholder: "브롤러 이름 입력", submit: "정답 제출", skip: "모르겠어요", imageAlt: "브롤러 실루엣 이미지", prompt: "이 실루엣의 브롤러는 누구일까요?", wrongAnswer: "정답이 아닙니다. 정답을 확인하고 다음 문제로 이동합니다.", skipped: "정답을 확인하고 다음 문제로 이동합니다." },
  en: { title: "Brawler Silhouette Quiz", description: "Identify the brawler from the silhouette.", metaDescription: "Take a 10-question challenge and identify Brawl Stars brawlers from their silhouettes.", rules: "Look at the silhouette and enter the brawler’s name. You get one answer per question.", pool: "{count} base brawlers available", baseMode: "Base brawlers", skinsMode: "Include skins", expertMode: "Silhouette expert", skinUnavailable: "Suitable skin images are not available, so this mode cannot be played yet.", inputLabel: "Brawler name", inputPlaceholder: "Enter a brawler name", submit: "Submit answer", skip: "I don't know", imageAlt: "Brawler silhouette image", prompt: "Which brawler is this?", wrongAnswer: "That is not correct. The answer is shown before the next question.", skipped: "The answer is shown before the next question." },
  ja: { title: "ブロウラー シルエットクイズ", description: "シルエットからブロウラーを当てましょう。", metaDescription: "シルエットを見てブロウラー名を当てる全10問のチャレンジに挑戦しましょう。", rules: "影だけを見てブロウラー名を入力します。各問題の回答は1回です。", pool: "出題できる基本ブロウラー：{count}人", baseMode: "基本ブロウラー", skinsMode: "スキンを含む", expertMode: "シルエット上級", skinUnavailable: "適切なスキン画像がないため、このモードはまだプレイできません。", inputLabel: "ブロウラー名", inputPlaceholder: "ブロウラー名を入力", submit: "回答する", skip: "わからない", imageAlt: "ブロウラーのシルエット画像", prompt: "このシルエットは誰でしょう？", wrongAnswer: "不正解です。次の問題の前に答えを表示します。", skipped: "次の問題の前に答えを表示します。" },
  "pt-br": { title: "Quiz de silhuetas de brawlers", description: "Descubra o brawler pela silhueta.", metaDescription: "Encare 10 perguntas e identifique os brawlers de Brawl Stars pelas silhuetas.", rules: "Observe a sombra e digite o nome do brawler. Há uma tentativa por pergunta.", pool: "{count} brawlers básicos disponíveis", baseMode: "Brawlers básicos", skinsMode: "Incluir skins", expertMode: "Especialista em silhuetas", skinUnavailable: "Ainda não há imagens adequadas de skins, então este modo não pode ser jogado.", inputLabel: "Nome do brawler", inputPlaceholder: "Digite o nome do brawler", submit: "Enviar resposta", skip: "Não sei", imageAlt: "Imagem da silhueta de um brawler", prompt: "Qual é este brawler?", wrongAnswer: "Resposta incorreta. O nome será mostrado antes da próxima pergunta.", skipped: "O nome será mostrado antes da próxima pergunta." },
  es: { title: "Adivina la silueta del brawler", description: "Identifica al brawler por su silueta.", metaDescription: "Resuelve 10 preguntas e identifica a los brawlers de Brawl Stars por su silueta.", rules: "Mira la sombra y escribe el nombre del brawler. Solo hay un intento por pregunta.", pool: "{count} brawlers básicos disponibles", baseMode: "Brawlers básicos", skinsMode: "Incluir aspectos", expertMode: "Experto en siluetas", skinUnavailable: "Aún no hay imágenes adecuadas de aspectos, así que este modo no está disponible.", inputLabel: "Nombre del brawler", inputPlaceholder: "Escribe el nombre del brawler", submit: "Enviar respuesta", skip: "No lo sé", imageAlt: "Silueta de un brawler", prompt: "¿Qué brawler es?", wrongAnswer: "No es correcto. Mostraremos la respuesta antes de la siguiente pregunta.", skipped: "Mostraremos la respuesta antes de la siguiente pregunta." },
  tr: { title: "Savaşçı Silüeti Testi", description: "Silüetten savaşçıyı tahmin et.", metaDescription: "Brawl Stars savaşçılarını silüetlerinden tanımak için 10 soruluk teste katıl.", rules: "Gölgeye bakıp savaşçının adını yaz. Her soru için bir cevap hakkın var.", pool: "Oynanabilir temel savaşçı: {count}", baseMode: "Temel savaşçılar", skinsMode: "Kostümler dahil", expertMode: "Silüet uzmanı", skinUnavailable: "Uygun kostüm görselleri bulunmadığı için bu mod henüz oynanamıyor.", inputLabel: "Savaşçı adı", inputPlaceholder: "Savaşçının adını yaz", submit: "Cevabı gönder", skip: "Bilmiyorum", imageAlt: "Savaşçı silüeti görseli", prompt: "Bu silüet hangi savaşçı?", wrongAnswer: "Yanlış cevap. Sonraki sorudan önce doğru cevap gösterilecek.", skipped: "Sonraki sorudan önce doğru cevap gösterilecek." },
  de: { title: "Brawler-Silhouettenquiz", description: "Erkenne den Brawler an seiner Silhouette.", metaDescription: "Erkenne Brawl-Stars-Brawler in einer Herausforderung mit zehn Fragen an ihrer Silhouette.", rules: "Sieh dir den Schatten an und gib den Namen des Brawlers ein. Pro Frage gibt es einen Versuch.", pool: "{count} Basis-Brawler verfügbar", baseMode: "Basis-Brawler", skinsMode: "Skins einbeziehen", expertMode: "Silhouetten-Profi", skinUnavailable: "Geeignete Skin-Bilder sind nicht verfügbar. Dieser Modus kann daher noch nicht gespielt werden.", inputLabel: "Brawler-Name", inputPlaceholder: "Brawler-Namen eingeben", submit: "Antwort senden", skip: "Weiß ich nicht", imageAlt: "Silhouette eines Brawlers", prompt: "Welcher Brawler ist das?", wrongAnswer: "Das ist leider falsch. Vor der nächsten Frage wird die Lösung gezeigt.", skipped: "Vor der nächsten Frage wird die Lösung gezeigt." },
  fr: { title: "Quiz des silhouettes de brawlers", description: "Reconnaissez le brawler à sa silhouette.", metaDescription: "Identifiez les brawlers de Brawl Stars grâce à leur silhouette dans un défi de 10 questions.", rules: "Observez l’ombre et saisissez le nom du brawler. Une seule réponse est possible par question.", pool: "{count} brawlers de base disponibles", baseMode: "Brawlers de base", skinsMode: "Inclure les skins", expertMode: "Expert en silhouettes", skinUnavailable: "Les images de skins adaptées ne sont pas disponibles. Ce mode ne peut pas encore être joué.", inputLabel: "Nom du brawler", inputPlaceholder: "Saisir le nom d’un brawler", submit: "Valider la réponse", skip: "Je ne sais pas", imageAlt: "Silhouette d’un brawler", prompt: "Quel est ce brawler ?", wrongAnswer: "Ce n’est pas la bonne réponse. La solution sera affichée avant la question suivante.", skipped: "La solution sera affichée avant la question suivante." },
  it: { title: "Quiz delle sagome dei brawler", description: "Riconosci il brawler dalla sua sagoma.", metaDescription: "Indovina i brawler di Brawl Stars dalle sagome in una sfida di 10 domande.", rules: "Guarda l’ombra e inserisci il nome del brawler. Hai un solo tentativo per domanda.", pool: "Brawler base disponibili: {count}", baseMode: "Brawler base", skinsMode: "Includi skin", expertMode: "Esperto di sagome", skinUnavailable: "Non sono disponibili immagini adatte delle skin, quindi questa modalità non è ancora giocabile.", inputLabel: "Nome del brawler", inputPlaceholder: "Inserisci il nome del brawler", submit: "Invia risposta", skip: "Non lo so", imageAlt: "Immagine della sagoma di un brawler", prompt: "Qual è questo brawler?", wrongAnswer: "Risposta sbagliata. Mostreremo la soluzione prima della domanda successiva.", skipped: "Mostreremo la soluzione prima della domanda successiva." },
  ru: { title: "Викторина по силуэтам бойцов", description: "Угадайте бойца по силуэту.", metaDescription: "Угадайте бойцов Brawl Stars по силуэтам в испытании из 10 вопросов.", rules: "Посмотрите на тень и введите имя бойца. На каждый вопрос даётся одна попытка.", pool: "Доступно обычных бойцов: {count}", baseMode: "Обычные бойцы", skinsMode: "Со скинами", expertMode: "Эксперт по силуэтам", skinUnavailable: "Подходящих изображений скинов нет, поэтому этот режим пока недоступен.", inputLabel: "Имя бойца", inputPlaceholder: "Введите имя бойца", submit: "Ответить", skip: "Не знаю", imageAlt: "Изображение силуэта бойца", prompt: "Кто изображён на силуэте?", wrongAnswer: "Неверно. Перед следующим вопросом будет показан ответ.", skipped: "Перед следующим вопросом будет показан ответ." },
} as const satisfies Record<Locale, Record<string, string>>;

export type SilhouetteMessages = (typeof messages)["ko"];
export function getSilhouetteMessages(locale: Locale): SilhouetteMessages { return messages[locale] as SilhouetteMessages; }
