import {
    generatedMapDict,
    generatedMapToModeDict,
    generatedModeDict,
} from "./generatedBrawlTranslations";

export const mapDict: Record<string, string> =
{
    // 젬 그랩 (Gem Grab)
    "Hard Rock Mine": "암석 광산",
    "Minecart Madness": "광기의 광산 열차",
    "Double Swoosh": "이중 곡선",
    "Undermine": "언더마인",
    "Crystal Arcade": "크리스털 오락실",
    "Deep Diner": "심연의 식당",
    "Gem Fort": "보석 요새",
    "Rustic Arcade": "시골 오락실",
    "Deathcap Cave": "독버섯 동굴",
    "Stone Fort": "돌무더기 요새",
    "Bouncing Diner": "바운스 식당",
    "Last Stand": "최후의 저항",
    "Acute Angle": "예각",
    "Solid Center": "단단한 중심",
    "Sillhouette": "실루엣",

    // 브롤 볼 (Brawl Ball)
    "Backyard Bowl": "뒷마당 월드컵",
    "Center Stage": "센터 스테이지",
    "Super Beach": "슈퍼 해변",
    "Pinball Dreams": "핀볼 드림",
    "Sneaky Fields": "스니키 필드",
    "Triple Dribble": "트리플 드리블",
    "Penalty Kick": "페널티 킥",
    "Beach Ball": "비치 볼",
    "Pinhole Punt": "바늘귀 통과",
    "Sunny Soccer": "화창한 축구장",
    "Encirclement": "포위 공격",
    "Field Goal": "필드 골",
    "Slalom": "슬랄롬",
    "Iron Corridors": "강철 회랑",
    "Goalkeeper's Dream": "골키퍼의 꿈",
    "Retina": "망막",

    // 쇼다운 (Showdown)
    "Feast or Famine": "모 아니면 도",
    "Skull Creek": "해골천",
    "Double Trouble": "이중 위협",
    "Rockwall Brawl": "바위 장벽 전투",
    "Acid Lakes": "산성 호수",
    "Cavern Churn": "우당탕 진흙탕",
    "Dark Passage": "어두운 통로",
    "Scorched Stone": "불타는 돌무더기",
    "Clash Colosseum": "클래시 콜로세움",
    "Riverside": "강가",
    "Safety Center": "안전 센터",
    "Island Invasion": "섬 침략",
    "Flying Fantasies": "날으는 환상",
    "Point of View": "관점",
    "Dune Drift": "사구 드리프트",
    "Forsaken Falls": "버려진 폭포",

    // 하이스트 (Heist)
    "Safe Zone": "안전 지대",
    "Hot Potato": "뜨거운 감자",
    "Pit Stop": "피트 스톱",
    "Kaboom Canyon": "우당탕 협곡",
    "Bridge Too Far": "머나먼 다리",
    "G.G. Mortuary": "G.G. 공동묘지",
    "Tornado Ring": "토네이도 링",
    "Snaked Assault": "뱀의 공격",
    "Forks Out": "갈림길",
    "Traffic Jam": "교통 체증",
    "Cover Crowd": "커버 크라우드",
    "Splitter": "스플리터",
    "Milky Way": "은하수",

    // 바운티 (Bounty)
    "Shooting Star": "별내림 계곡",
    "Canal Grande": "운하 협곡",
    "Layer Cake": "레이어 케이크",
    "Excel": "엑셀",
    "Snake Prairie": "뱀의 초원",
    "Dry Season": "건조기",
    "Temple Ruins": "사원 폐허",
    "Hideout": "은신처",
    "Overgrown Oasis": "우거진 오아시스",
    "Purple Paradise": "퍼플 파라다이스",

    // 핫 존 (Hot Zone)
    "Ring of Fire": "불의 고리",
    "Dueling Beetles": "곤충 싸움",
    "Open Business": "오픈 비즈니스",
    "Parallel Plays": "평행선",
    "Split": "분할",
    "Quarter Pounder": "쿼터 파운더",
    "Triumvirate": "삼두정치",
    "Night Museum": "야간 박물관",
    "Massive Attack": "대규모 공격",

    // 녹아웃 (Knockout)
    "Goldarm Gulch": "골드암 골짜기",
    "Flaring Phoenix": "불타는 불사조",
    "Belle's Rock": "벨의 바위",
    "Out in the Open": "탁 트인 공간",
    "New Perspective": "새로운 시각",
    "Deep End": "깊은 곳",
    "X Marks the Spot": "X 표시",
    "Healthy Middle Ground": "건강한 타협점",
    "Belles Rock": "벨의 바위",
    "Four Levels": "네 개의 레벨",
    "Flowing Springs": "흐르는 샘",
    "Waters of Doom": "파멸의 물",

    // 와이프아웃 (Wipeout)
    "Infinite Doom": "무한한 파멸",
    "Quad Damage": "쿼드 데미지",
    "The Great Open": "탁 트인 공간",
    "Pain in the Grass": "초원의 고통",
    ...generatedMapDict,
};

export const mapToModeDict: Record<string, string> =
{
    // 젬 그랩
    "Hard Rock Mine": "젬 그랩",
    "Minecart Madness": "젬 그랩",
    "Double Swoosh": "젬 그랩",
    "Undermine": "젬 그랩",
    "Crystal Arcade": "젬 그랩",
    "Deep Diner": "젬 그랩",
    "Gem Fort": "젬 그랩",
    "Rustic Arcade": "젬 그랩",
    "Deathcap Cave": "젬 그랩",
    "Stone Fort": "젬 그랩",
    "Bouncing Diner": "젬 그랩",
    "Last Stand": "젬 그랩",
    "Acute Angle": "젬 그랩",
    "Solid Center": "젬 그랩",
    "Sillhouette": "젬 그랩",

    // 브롤 볼
    "Backyard Bowl": "브롤 볼",
    "Center Stage": "브롤 볼",
    "Super Beach": "브롤 볼",
    "Pinball Dreams": "브롤 볼",
    "Sneaky Fields": "브롤 볼",
    "Triple Dribble": "브롤 볼",
    "Penalty Kick": "브롤 볼",
    "Beach Ball": "브롤 볼",
    "Pinhole Punt": "브롤 볼",
    "Sunny Soccer": "브롤 볼",
    "Encirclement": "브롤 볼",
    "Field Goal": "브롤 볼",
    "Slalom": "브롤 볼",
    "Iron Corridors": "브롤 볼",
    "Goalkeeper's Dream": "브롤 볼",
    "Retina": "브롤 볼",

    // 쇼다운
    "Feast or Famine": "쇼다운",
    "Skull Creek": "쇼다운",
    "Double Trouble": "쇼다운",
    "Rockwall Brawl": "쇼다운",
    "Acid Lakes": "쇼다운",
    "Cavern Churn": "쇼다운",
    "Dark Passage": "쇼다운",
    "Scorched Stone": "쇼다운",
    "Clash Colosseum": "쇼다운",
    "Riverside": "쇼다운",
    "Safety Center": "쇼다운",
    "Island Invasion": "쇼다운",
    "Flying Fantasies": "쇼다운",
    "Point of View": "쇼다운",
    "Dune Drift": "쇼다운",
    "Forsaken Falls": "쇼다운",

    // 하이스트
    "Safe Zone": "하이스트",
    "Hot Potato": "하이스트",
    "Pit Stop": "하이스트",
    "Kaboom Canyon": "하이스트",
    "Bridge Too Far": "하이스트",
    "G.G. Mortuary": "하이스트",
    "Tornado Ring": "하이스트",
    "Snaked Assault": "하이스트",
    "Forks Out": "하이스트",
    "Traffic Jam": "하이스트",
    "Cover Crowd": "하이스트",
    "Splitter": "하이스트",
    "Milky Way": "하이스트",

    // 바운티
    "Shooting Star": "바운티",
    "Canal Grande": "바운티",
    "Layer Cake": "바운티",
    "Excel": "바운티",
    "Snake Prairie": "바운티",
    "Dry Season": "바운티",
    "Temple Ruins": "바운티",
    "Hideout": "바운티",
    "Overgrown Oasis": "바운티",
    "Purple Paradise": "바운티",

    // 핫 존
    "Ring of Fire": "핫 존",
    "Dueling Beetles": "핫 존",
    "Open Business": "핫 존",
    "Parallel Plays": "핫 존",
    "Split": "핫 존",
    "Quarter Pounder": "핫 존",
    "Triumvirate": "핫 존",
    "Night Museum": "핫 존",
    "Massive Attack": "핫 존",

    // 녹아웃
    "Goldarm Gulch": "녹아웃",
    "Flaring Phoenix": "녹아웃",
    "Belle's Rock": "녹아웃",
    "Belles Rock": "녹아웃",
    "Out in the Open": "녹아웃",
    "New Perspective": "녹아웃",
    "Deep End": "녹아웃",
    "X Marks the Spot": "녹아웃",
    "Healthy Middle Ground": "녹아웃",
    "Four Levels": "녹아웃",
    "Flowing Springs": "녹아웃",
    "Waters of Doom": "녹아웃",

    // 와이프아웃
    "Infinite Doom": "와이프아웃",
    "Quad Damage": "와이프아웃",
    "The Great Open": "와이프아웃",
    "Pain in the Grass": "기타",
    ...generatedMapToModeDict,
};

export const rankDict: Record<string, string> =
{
    "BRONZE I": "브론즈 I",
    "BRONZE II": "브론즈 II",
    "BRONZE III": "브론즈 III",
    "SILVER I": "실버 I",
    "SILVER II": "실버 II",
    "SILVER III": "실버 III",
    "GOLD I": "골드 I",
    "GOLD II": "골드 II",
    "GOLD III": "골드 III",
    "DIAMOND I": "다이아몬드 I",
    "DIAMOND II": "다이아몬드 II",
    "DIAMOND III": "다이아몬드 III",
    "MYTHIC I": "신화 I",
    "MYTHIC II": "신화 II",
    "MYTHIC III": "신화 III",
    "LEGENDARY I": "전설 I",
    "LEGENDARY II": "전설 II",
    "LEGENDARY III": "전설 III",
    "MASTERS I": "마스터 I",
    "MASTERS II": "마스터 II",
    "MASTERS III": "마스터 III",
    "PRO": "프로",
};

export const modeDict: Record<string, string> =
{
    brawlBall: "브롤 볼",
    gemGrab: "젬 그랩",
    soloShowdown: "솔로 쇼다운",
    duoShowdown: "듀오 쇼다운",
    heist: "하이스트",
    bounty: "바운티",
    hotZone: "핫 존",
    knockout: "녹아웃",
    wipeout: "와이프아웃",
    duels: "듀얼",
    trioShowdown: "트리오 쇼다운",
    friendly: "친선",
    ...generatedModeDict,
};

export const brawlerDict: Record<string, string> =
{
    SHELLY: "쉘리",
    NITA: "니타",
    COLT: "콜트",
    BULL: "불",
    BROCK: "브록",
    "EL PRIMO": "엘 프리모",
    BARLEY: "발리",
    POCO: "포코",
    ROSA: "로사",
    JESSIE: "제시",
    DYNAMIKE: "다이너마이크",
    TICK: "틱",
    "8-BIT": "8비트",
    RICO: "리코",
    DARRYL: "대릴",
    PENNY: "페니",
    CARL: "칼",
    JACKY: "재키",
    PIPER: "파이퍼",
    PAM: "팸",
    FRANK: "프랭크",
    BIBI: "비비",
    BEA: "비",
    NANI: "나니",
    EDGAR: "에드거",
    GRIFF: "그리프",
    GROM: "그롬",
    MORTIS: "모티스",
    TARA: "타라",
    GENE: "진",
    MAX: "맥스",
    "MR. P": "미스터 P",
    SPROUT: "스프라우트",
    BYRON: "바이런",
    SQUEAK: "스퀴크",
    SPIKE: "스파이크",
    CROW: "크로우",
    LEON: "레온",
    SANDY: "샌디",
    AMBER: "앰버",
    MEG: "메그",
    SURGE: "서지",
    COLETTE: "콜레트",
    LOU: "루",
    RUFFS: "러프스",
    BELLE: "벨",
    BUZZ: "버즈",
    ASH: "애쉬",
    LOLA: "롤라",
    FANG: "팽",
    EVE: "이브",
    JANET: "자넷",
    OTIS: "오티스",
    SAM: "샘",
    BUSTER: "버스터",
    MANDY: "맨디",
    "R-T": "R-T",
    WILLOW: "윌로우",
    MAISIE: "메이지",
    HANK: "행크",
    CORDELIUS: "코델리우스",
    DOUG: "더그",
    PEARL: "펄",
    CHUCK: "척",
    CHARLIE: "찰리",
    MICO: "미코",
    KIT: "키트",
    "LARRY & LAWRIE": "래리 & 로리",
    MELODIE: "멜로디",
    ANGELO: "안젤로",
    LILY: "릴리",
    DRACO: "드라코",
    BERRY: "베리",
    CLANCY: "클랜시",
    MOE: "모",
    KENJI: "켄지",
    JUJU: "주주",
    SHADE: "셰이드",
    GALE: "게일",
    CHESTER: "체스터",
    BO: "보",
    EMZ: "엠즈",
    STU: "스튜",
    DEMIAN: "데미안",
    DAMIAN: "데미안",
    LUMI: "루미",
    "STARR NOVA": "스타 노바",
    BOLT: "볼트",
    PIERCE: "피어스",
    MINA: "미나",
    MEEPLE: "미플",
    ZIGGY: "지기",
    OLLIE: "올리",
    GLOWY: "글로이",
    GLOWBERT: "글로버트",
    TRUNK: "트렁크",
    ALLI: "알리",
    FINX: "핑크스",
    "JAE-YONG": "재용",
    GIGI: "지지",
    KAZE: "카제",
    NAJIA: "나지아",
    SIRIUS: "시리우스",
    BONNIE: "보니",
    GRAY: "그레이",
    GUS: "거스"
};
