export const mapDict: any = 
{
    // 젬 그랩
    "Hard Rock Mine": "암석 광산",
    "Double Swoosh": "이중 곡선",
    "Minecart Madness": "광기의 광산 열차",
    "Crystal Arcade": "크리스털 오락실",
    "Undermine": "언더마인",
    
    // 브롤 볼
    "Backyard Bowl": "뒷마당 월드컵",
    "Center Stage": "센터 스테이지",
    "Super Beach": "슈퍼 해변",
    "Pinball Dreams": "핀볼 드림",
    "Sneaky Fields": "스니키 필드",
    
    // 쇼다운 (솔로/듀오)
    "Feast or Famine": "모 아니면 도",
    "Skull Creek": "해골 천천",
    "Double Trouble": "이중 위협",
    "Rockwall Brawl": "바위 장벽 전투",
    "Acid Lakes": "산성 호수",
    
    // 하이스트
    "Safe Zone": "안전 지대",
    "Hot Potato": "뜨거운 감자",
    "Pit Stop": "피트 스톱",
    "Kaboom Canyon": "우당탕 협곡",
    
    // 바운티
    "Shooting Star": "별내림 계곡",
    "Canal Grande": "운하 협곡",
    "Layer Cake": "레이어 케이크",
    "Excel": "엑셀",
    
    // 핫 존
    "Ring of Fire": "불의 고리",
    "Dueling Beetles": "곤충 싸움",
    "Open Business": "오픈 비즈니스",
    
    // 녹아웃
    "Goldarm Gulch": "골드암 골짜기",
    "Flaring Phoenix": "불타는 불사조",
    "Belle's Rock": "벨의 바위",
    "Out in the Open": "탁 트인 공간"
};

export const rankDict: any = 
{
};

export const modeDict: any = 
{
    brawlBall: "브롤 볼",
    gemGrab: "젬 그랩",
    soloShowdown: "솔로 쇼다운",
    duoShowdown: "듀오 쇼다운",
    heist: "하이스트",
    bounty: "바운티",
    hotZone: "핫 존",
    knockout: "녹아웃",
    wipeout: "와이프아웃",
    duels: "듀얼",
    trioShowdown: "트리오 쇼다운"
};

export const brawlerDict: any = 
{
    SHELLY: "쉘리",
    NITA: "니타",
    COLT: "콜트",
    BULL: "불",
    BROCK: "브록",
    "EL PRIMO": "엘 프리모",
    BARLEY: "발리",
    POCO: "포코",
    ROSA: "로사",
    JESSIE: "제시",
    DYNAMIKE: "다이너마이크",
    TICK: "틱",
    "8-BIT": "8비트",
    RICO: "리코",
    DARRYL: "대릴",
    PENNY: "페니",
    CARL: "칼",
    JACKY: "재키",
    PIPER: "파이퍼",
    PAM: "팸",
    FRANK: "프랭크",
    BIBI: "비비",
    BEA: "비",
    NANI: "나니",
    EDGAR: "에드거",
    GRIFF: "그리프",
    GROM: "그롬",
    MORTIS: "모티스",
    TARA: "타라",
    GENE: "진",
    MAX: "맥스",
    "MR. P": "미스터 P",
    SPROUT: "스프라우트",
    BYRON: "바이런",
    SQUEAK: "스퀴크",
    SPIKE: "스파이크",
    CROW: "크로우",
    LEON: "레온",
    SANDY: "샌디",
    AMBER: "앰버",
    MEG: "메그",
    SURGE: "서지",
    COLETTE: "콜레트",
    LOU: "루",
    RUFFS: "러프스",
    BELLE: "벨",
    BUZZ: "버즈",
    ASH: "애쉬",
    LOLA: "롤라",
    FANG: "팽",
    EVE: "이브",
    JANET: "자넷",
    OTIS: "오티스",
    SAM: "샘",
    BUSTER: "버스터",
    MANDY: "맨디",
    "R-T": "R-T",
    WILLOW: "윌로우",
    MAISIE: "메이지",
    HANK: "행크",
    CORDELIUS: "코델리우스",
    DOUG: "더그",
    PEARL: "펄",
    CHUCK: "척",
    CHARLIE: "찰리",
    MICO: "미코",
    KIT: "키트",
    "LARRY & LAWRIE": "래리 & 로리",
    MELODIE: "멜로디",
    ANGELO: "안젤로",
    LILY: "릴리",
    DRACO: "드라코",
    BERRY: "베리",
    CLANCY: "클랜시",
    MOE: "모",
    KENJI: "켄지",
    JUJU: "주주",
    SHADE: "셰이드",
    GALE: "게일",
    CHESTER: "체스터",
    BO: "보",
    EMZ: "엠즈",
    STU: "스튜",
    DEMIAN: "데미안",
    DAMIAN: "데미안",
    LUMI: "루미",
    "STARR NOVA": "스타 노바",
    BOLT: "볼트",
    PIERCE: "피어스",
    MINA: "미나",
    MEEPLE: "미플",
    ZIGGY: "지기",
    OLLIE: "올리",
    GLOWY: "글로이",
    GLOWBERT: "글로버트",
    TRUNK: "트렁크",
    ALLI: "알리",
    FINX: "핑스",
    "JAE-YONG": "재용",
    GIGI: "지지",
    KAZE: "카제",
    NAJIA: "나지아",
    SIRIUS: "시리우스",
    BONNIE: "보니",
    GRAY: "그레이",
    GUS: "거스"
};