// Generated by scripts/update-minigame-assets.mjs. Do not edit manually.
// Source: https://github.com/Brawlify/CDN at 45eabc3ebd910c6998c1abd3cf21d9fe970dab15
// Update with: npm run minigames:assets:update
export type BrawlerModelAsset = { brawlerId: number; path: string; blobSha: string };
export const brawlerModelSource = { repository: "Brawlify/CDN", commitSha: "45eabc3ebd910c6998c1abd3cf21d9fe970dab15" } as const;
export const generatedBrawlerModels: readonly BrawlerModelAsset[] = [
  {
    "brawlerId": 16000000,
    "path": "brawlers/model/16000000.png",
    "blobSha": "82ef1b316db4824799f7330756aaee2850ff059c"
  },
  {
    "brawlerId": 16000001,
    "path": "brawlers/model/16000001.png",
    "blobSha": "495f265ca9f68659c57864842b38687854d1c573"
  },
  {
    "brawlerId": 16000002,
    "path": "brawlers/model/16000002.png",
    "blobSha": "2a677497a588c100b2f531da15b5b97d257ed640"
  },
  {
    "brawlerId": 16000003,
    "path": "brawlers/model/16000003.png",
    "blobSha": "6169d1eadb6ae6afa836b267ea4cf2cf3583be38"
  },
  {
    "brawlerId": 16000004,
    "path": "brawlers/model/16000004.png",
    "blobSha": "0019360f482d556de6321d6bf6924170067fb705"
  },
  {
    "brawlerId": 16000005,
    "path": "brawlers/model/16000005.png",
    "blobSha": "863d32ba7234ab6fe67a31373bdaca19270eaeef"
  },
  {
    "brawlerId": 16000006,
    "path": "brawlers/model/16000006.png",
    "blobSha": "0a2c23d099374a2507812bae144b428bf68c2bfb"
  },
  {
    "brawlerId": 16000007,
    "path": "brawlers/model/16000007.png",
    "blobSha": "8dd3d1aa6987c9f945ac2eee6d417d26eb70abdc"
  },
  {
    "brawlerId": 16000008,
    "path": "brawlers/model/16000008.png",
    "blobSha": "80ce0ebdb1978c4553029e5ffa80a7238dcb3b36"
  },
  {
    "brawlerId": 16000009,
    "path": "brawlers/model/16000009.png",
    "blobSha": "2b1f2fb2b10bf5bffd0a88ee22b5ded33fa38b43"
  },
  {
    "brawlerId": 16000010,
    "path": "brawlers/model/16000010.png",
    "blobSha": "852d5bd00f8b76a08965ad2891de44e4c4d77da0"
  },
  {
    "brawlerId": 16000011,
    "path": "brawlers/model/16000011.png",
    "blobSha": "d8d66d9752662f84b62155caa74aac2d2832dfa1"
  },
  {
    "brawlerId": 16000012,
    "path": "brawlers/model/16000012.png",
    "blobSha": "886b74e9c2ed902108387d3a33b4989565be0f17"
  },
  {
    "brawlerId": 16000013,
    "path": "brawlers/model/16000013.png",
    "blobSha": "892f81032610092342c521804774e51cb368e405"
  },
  {
    "brawlerId": 16000014,
    "path": "brawlers/model/16000014.png",
    "blobSha": "4f3f0a745e3a5143d7152001949c38e3e845c167"
  },
  {
    "brawlerId": 16000015,
    "path": "brawlers/model/16000015.png",
    "blobSha": "000153f316db4e0a95553a12fb801982a049be9a"
  },
  {
    "brawlerId": 16000016,
    "path": "brawlers/model/16000016.png",
    "blobSha": "be753d483cc695cf20bdeb02f506b26debc58a3c"
  },
  {
    "brawlerId": 16000017,
    "path": "brawlers/model/16000017.png",
    "blobSha": "296996918fd63244083018c1242e4e7cfc4960aa"
  },
  {
    "brawlerId": 16000018,
    "path": "brawlers/model/16000018.png",
    "blobSha": "fb9ed8e1caf21bcf5575c7a207649a7c443b5db6"
  },
  {
    "brawlerId": 16000019,
    "path": "brawlers/model/16000019.png",
    "blobSha": "71bc72224ba301e695e5b6f9b5988c445ff3e789"
  },
  {
    "brawlerId": 16000020,
    "path": "brawlers/model/16000020.png",
    "blobSha": "23de9542dee81e4fd53ba83cebd96bf4fdf87b87"
  },
  {
    "brawlerId": 16000021,
    "path": "brawlers/model/16000021.png",
    "blobSha": "c524906f541fe0a9ca7c4790c25af1d9e6a3d606"
  },
  {
    "brawlerId": 16000022,
    "path": "brawlers/model/16000022.png",
    "blobSha": "14a4ce4705645e90c2d43dafe32d8a1b775115bc"
  },
  {
    "brawlerId": 16000023,
    "path": "brawlers/model/16000023.png",
    "blobSha": "30f31dc67280d623fdc14e83580f9b87f8416914"
  },
  {
    "brawlerId": 16000024,
    "path": "brawlers/model/16000024.png",
    "blobSha": "08f8eeb9964dd1dd7ed52de0db05cee0dbc61306"
  },
  {
    "brawlerId": 16000025,
    "path": "brawlers/model/16000025.png",
    "blobSha": "48487af3d4050c266ebc173966643e87a5fbd2e2"
  },
  {
    "brawlerId": 16000026,
    "path": "brawlers/model/16000026.png",
    "blobSha": "749b3581fd3dff1fb1138a90a388cadc902014ab"
  },
  {
    "brawlerId": 16000027,
    "path": "brawlers/model/16000027.png",
    "blobSha": "483310e50f3c8c9924f63281b68eab22582c76d1"
  },
  {
    "brawlerId": 16000028,
    "path": "brawlers/model/16000028.png",
    "blobSha": "80c4f30a8a3815ab51e740a655422a7e6f9e4056"
  },
  {
    "brawlerId": 16000029,
    "path": "brawlers/model/16000029.png",
    "blobSha": "3ecba364a95c5bc6374dfa9c5963955342786814"
  },
  {
    "brawlerId": 16000030,
    "path": "brawlers/model/16000030.png",
    "blobSha": "74445089a3e09b644bf481f13a0b7ce76f7d2abd"
  },
  {
    "brawlerId": 16000031,
    "path": "brawlers/model/16000031.png",
    "blobSha": "c2d2807f364e6a54da8b62c299319911291bf567"
  },
  {
    "brawlerId": 16000032,
    "path": "brawlers/model/16000032.png",
    "blobSha": "b609f56276ca2a7f841ffaef19e6239d133a1dce"
  },
  {
    "brawlerId": 16000034,
    "path": "brawlers/model/16000034.png",
    "blobSha": "078d0138321ca886208d0a9a9d9b4f2abc27efd1"
  },
  {
    "brawlerId": 16000035,
    "path": "brawlers/model/16000035.png",
    "blobSha": "eb55827287c7177e1a8210a7a8215f2109079d86"
  },
  {
    "brawlerId": 16000036,
    "path": "brawlers/model/16000036.png",
    "blobSha": "ece2d54fd715a469d98a21dacabff4aaf9c56c04"
  },
  {
    "brawlerId": 16000037,
    "path": "brawlers/model/16000037.png",
    "blobSha": "05d72629c7f45f3f79a65f16adb9e30db1dc555d"
  },
  {
    "brawlerId": 16000038,
    "path": "brawlers/model/16000038.png",
    "blobSha": "4d5cb687c1fbb41e6c78da4345a6f1a684269f32"
  },
  {
    "brawlerId": 16000039,
    "path": "brawlers/model/16000039.png",
    "blobSha": "dcc2b2fce6fa9ed0ea0dd26f3d13c8a9a87bf309"
  },
  {
    "brawlerId": 16000040,
    "path": "brawlers/model/16000040.png",
    "blobSha": "6c2101cb7b57de3fd7fcd41cb9b01cdd9a407851"
  },
  {
    "brawlerId": 16000041,
    "path": "brawlers/model/16000041.png",
    "blobSha": "e1750a620658776ceb149bb46889aa10ec7b86e6"
  },
  {
    "brawlerId": 16000042,
    "path": "brawlers/model/16000042.png",
    "blobSha": "c27ac41e0a97f6f070ac500528b12e2201f9bc9c"
  },
  {
    "brawlerId": 16000043,
    "path": "brawlers/model/16000043.png",
    "blobSha": "1759d7be8adef5e292ebea7b9b299d2661b88673"
  },
  {
    "brawlerId": 16000044,
    "path": "brawlers/model/16000044.png",
    "blobSha": "970acd4a24320c583be0f5c7a8caab3307836352"
  },
  {
    "brawlerId": 16000045,
    "path": "brawlers/model/16000045.png",
    "blobSha": "ddf70d78b53c0e7e8ac0537c508fffda76b55fc6"
  },
  {
    "brawlerId": 16000046,
    "path": "brawlers/model/16000046.png",
    "blobSha": "e03628d54f2d7d9f64c607b5ac88d828301bc036"
  },
  {
    "brawlerId": 16000047,
    "path": "brawlers/model/16000047.png",
    "blobSha": "db2fd6ad527cab7a15c3c4561c9a28b2412e4325"
  },
  {
    "brawlerId": 16000048,
    "path": "brawlers/model/16000048.png",
    "blobSha": "e23fd4dfdf987170e55c513ddfc7e3208d06b064"
  },
  {
    "brawlerId": 16000049,
    "path": "brawlers/model/16000049.png",
    "blobSha": "d017bfe294b8a237761c852e554ff8d77fb47ba7"
  },
  {
    "brawlerId": 16000050,
    "path": "brawlers/model/16000050.png",
    "blobSha": "3cbcd7de5df2722bebd7dfd8b84ad83a258e9d51"
  },
  {
    "brawlerId": 16000051,
    "path": "brawlers/model/16000051.png",
    "blobSha": "c34c12a5d7563efb16fd573ec33b699a1222a864"
  },
  {
    "brawlerId": 16000052,
    "path": "brawlers/model/16000052.png",
    "blobSha": "2e441f2c9ff9007995420462617805d00ea30681"
  },
  {
    "brawlerId": 16000053,
    "path": "brawlers/model/16000053.png",
    "blobSha": "237c45536478303088fa32b46cca6c13cb2ffc83"
  },
  {
    "brawlerId": 16000054,
    "path": "brawlers/model/16000054.png",
    "blobSha": "6a20770423aaaaec5d611a14f075612c21a8486f"
  },
  {
    "brawlerId": 16000056,
    "path": "brawlers/model/16000056.png",
    "blobSha": "130ed210f31232e3774781625acea5602acb395e"
  },
  {
    "brawlerId": 16000057,
    "path": "brawlers/model/16000057.png",
    "blobSha": "c112ac80afbe408a7f41632e63622675c55406a1"
  },
  {
    "brawlerId": 16000058,
    "path": "brawlers/model/16000058.png",
    "blobSha": "10d9ec8ffecc55e70b52578cb4a035c89148a5c3"
  },
  {
    "brawlerId": 16000059,
    "path": "brawlers/model/16000059.png",
    "blobSha": "59d3629dda7dd449fe8a21974c7fd04671aade1b"
  },
  {
    "brawlerId": 16000060,
    "path": "brawlers/model/16000060.png",
    "blobSha": "47d661732d49b4d5727ff143a69da7224dcefaca"
  },
  {
    "brawlerId": 16000061,
    "path": "brawlers/model/16000061.png",
    "blobSha": "24d9175c7f7fd23a31df28fcf781472735665898"
  },
  {
    "brawlerId": 16000062,
    "path": "brawlers/model/16000062.png",
    "blobSha": "7e9863663d197ad998b04bb1715ee8905d793181"
  },
  {
    "brawlerId": 16000063,
    "path": "brawlers/model/16000063.png",
    "blobSha": "10bc9a60ce0905939b51380ea84c74e0a8055b0b"
  },
  {
    "brawlerId": 16000064,
    "path": "brawlers/model/16000064.png",
    "blobSha": "3e22406f70567312b2e5c534e334e3ee2eddd2ef"
  },
  {
    "brawlerId": 16000065,
    "path": "brawlers/model/16000065.png",
    "blobSha": "a0d86643bc975c5ddffb0dbb739b2969a540d419"
  },
  {
    "brawlerId": 16000066,
    "path": "brawlers/model/16000066.png",
    "blobSha": "7dadfc102a2ab5916b60792f263fe661ecdfea31"
  },
  {
    "brawlerId": 16000067,
    "path": "brawlers/model/16000067.png",
    "blobSha": "3bf28549dfb37f52d7f205badbb08503c56e1248"
  },
  {
    "brawlerId": 16000068,
    "path": "brawlers/model/16000068.png",
    "blobSha": "97ce9fa330043dbeae192a40bdd8c10828173c62"
  },
  {
    "brawlerId": 16000069,
    "path": "brawlers/model/16000069.png",
    "blobSha": "34aa37ec54bdcf65a0cba345e6885a2935d1dbd5"
  },
  {
    "brawlerId": 16000070,
    "path": "brawlers/model/16000070.png",
    "blobSha": "b1d7a64b2a00d92afb4d1fd017bf60549c38ea01"
  },
  {
    "brawlerId": 16000071,
    "path": "brawlers/model/16000071.png",
    "blobSha": "207ab8c9e19b1c2434a91bd20a88f612b27cf050"
  },
  {
    "brawlerId": 16000072,
    "path": "brawlers/model/16000072.png",
    "blobSha": "717e25ea435814cdc3c3e64b8bc04e2171608395"
  },
  {
    "brawlerId": 16000073,
    "path": "brawlers/model/16000073.png",
    "blobSha": "54c7f65c8f8374af57a92c1039cd8901e5bc536e"
  },
  {
    "brawlerId": 16000074,
    "path": "brawlers/model/16000074.png",
    "blobSha": "f83069de1767f95c8367c567feb9e2626b11ebf7"
  },
  {
    "brawlerId": 16000075,
    "path": "brawlers/model/16000075.png",
    "blobSha": "f5a05eb993207799543ce625a5e92f916bde0c7d"
  },
  {
    "brawlerId": 16000076,
    "path": "brawlers/model/16000076.png",
    "blobSha": "b5fd9e5f92e3cd733fed9ee5eadb08b9422b6842"
  },
  {
    "brawlerId": 16000077,
    "path": "brawlers/model/16000077.png",
    "blobSha": "03824d8a7a4a07d782903477d53ad2f67ba46719"
  },
  {
    "brawlerId": 16000078,
    "path": "brawlers/model/16000078.png",
    "blobSha": "908a8bc0452999a8a2842f1a20f12c442104a47e"
  },
  {
    "brawlerId": 16000079,
    "path": "brawlers/model/16000079.png",
    "blobSha": "849654573d0aa70075a74cc957d328e86715f1bc"
  },
  {
    "brawlerId": 16000080,
    "path": "brawlers/model/16000080.png",
    "blobSha": "ecb978ed0088891c1cad61a238e6937cd597485e"
  },
  {
    "brawlerId": 16000081,
    "path": "brawlers/model/16000081.png",
    "blobSha": "bfde98933d4b9ba7079158dafdd3aa30dfdcf4f0"
  },
  {
    "brawlerId": 16000082,
    "path": "brawlers/model/16000082.png",
    "blobSha": "51645241a00902a37576b8c4376b0998e907804d"
  },
  {
    "brawlerId": 16000083,
    "path": "brawlers/model/16000083.png",
    "blobSha": "0a9a7ee4db019e7030911e848ab85f9b8395f591"
  },
  {
    "brawlerId": 16000084,
    "path": "brawlers/model/16000084.png",
    "blobSha": "d40de4966c5c4b96459d3100357b4258b7e32ef0"
  },
  {
    "brawlerId": 16000085,
    "path": "brawlers/model/16000085.png",
    "blobSha": "2f956133148a717b6c0f56a5afa6894da60c5184"
  },
  {
    "brawlerId": 16000086,
    "path": "brawlers/model/16000086.png",
    "blobSha": "4a23e26d3c5581c5a8e9fe9370d79e076a79532a"
  },
  {
    "brawlerId": 16000087,
    "path": "brawlers/model/16000087.png",
    "blobSha": "aa8757baa37048044aa3f66c4325e98c1e8a995d"
  },
  {
    "brawlerId": 16000088,
    "path": "brawlers/model/16000088.png",
    "blobSha": "a0dd7f88c595237562a7ce8607510fc256a0d81e"
  },
  {
    "brawlerId": 16000089,
    "path": "brawlers/model/16000089.png",
    "blobSha": "5a7338a250466132d8103e2eb1c5a219535f31c8"
  },
  {
    "brawlerId": 16000090,
    "path": "brawlers/model/16000090.png",
    "blobSha": "70f1c7e2d0c131f55968259ad0b63bc9761e1e5b"
  },
  {
    "brawlerId": 16000091,
    "path": "brawlers/model/16000091.png",
    "blobSha": "383404a940695cdeba3c3a148aaff1307419d046"
  },
  {
    "brawlerId": 16000092,
    "path": "brawlers/model/16000092.png",
    "blobSha": "631b29fa3f3621aab69b884f6bd4bdb6d332e8cc"
  },
  {
    "brawlerId": 16000093,
    "path": "brawlers/model/16000093.png",
    "blobSha": "85f67220ee5a533ad04e095bb84b888c8ad79938"
  },
  {
    "brawlerId": 16000094,
    "path": "brawlers/model/16000094.png",
    "blobSha": "3026b8052c0d70f4cf69170ad2853a9f02e04780"
  },
  {
    "brawlerId": 16000095,
    "path": "brawlers/model/16000095.png",
    "blobSha": "4ccdd852882921ffde57a381c768c682f29d8920"
  },
  {
    "brawlerId": 16000096,
    "path": "brawlers/model/16000096.png",
    "blobSha": "be561f0f6c255ad8082bf42dac731e3aa9e18eb0"
  },
  {
    "brawlerId": 16000097,
    "path": "brawlers/model/16000097.png",
    "blobSha": "78f313870925536e9e95032db2f602dc9f8c2720"
  },
  {
    "brawlerId": 16000098,
    "path": "brawlers/model/16000098.png",
    "blobSha": "56243a14154f74e1bb3016fb4cd6286c72027a7f"
  },
  {
    "brawlerId": 16000099,
    "path": "brawlers/model/16000099.png",
    "blobSha": "877fb06f5b5a3af664bb40161b0daceeec26de84"
  },
  {
    "brawlerId": 16000100,
    "path": "brawlers/model/16000100.png",
    "blobSha": "f806afc71513138b623ec4e1d7b33cc16d32c795"
  },
  {
    "brawlerId": 16000101,
    "path": "brawlers/model/16000101.png",
    "blobSha": "aaf837262022e599347d0d95edfe01ba8d4d72d6"
  },
  {
    "brawlerId": 16000102,
    "path": "brawlers/model/16000102.png",
    "blobSha": "b81918b43a3874b33ea03b6c3d2af2cd0347d7d4"
  },
  {
    "brawlerId": 16000103,
    "path": "brawlers/model/16000103.png",
    "blobSha": "a3a1db2dd0bf4ea2aede02b1c0f9ea5a58cdfc64"
  },
  {
    "brawlerId": 16000104,
    "path": "brawlers/model/16000104.png",
    "blobSha": "cac36b3ea0633681779683978cfcd448252cfe62"
  },
  {
    "brawlerId": 16000105,
    "path": "brawlers/model/16000105.png",
    "blobSha": "48dce9aa8ef12d562ebc4f13cd4adcb5e9fe680b"
  },
  {
    "brawlerId": 16000106,
    "path": "brawlers/model/16000106.png",
    "blobSha": "8ecf87598cd4e04a9ec642969b81dbcc184619a4"
  }
];
